### ISSUE TITLE
这个./cls_freq/CIFAR-10-LT_IMBA200.json忘传了么？

### ISSUE THREAD

**Issue by daixiangzi** [jiawei-ren/BalancedMetaSoftmax-Classification#1]

**Comment by hs8945** [comment]
same question

**Comment by jiawei-ren** [comment]
There is no need to worry about the class frequency file. `./cls_freq/CIFAR-10-LT_IMBA200.json` will be automatically dumped when building the dataset (by this [code](https://github.com/jiawei-ren/BalancedMetaSoftmax-Classification/blob/main/data/ImbalanceCIFAR.py#L69)). Just leave the config as it is and you should be good to go.
