### ISSUE TITLE
a question about proof

### ISSUE THREAD

**Issue by madoka109** [jiawei-ren/BalancedMetaSoftmax-Classification#14]
Thanks for your brilliant work! Besides, I have a question about proof in SecA.1.
![图片](https://user-images.githubusercontent.com/79368885/196080780-755207e0-f9a8-4175-824a-2092ca60780b.png)
I can't understand eqn.15, how to get this eq? 
![图片](https://user-images.githubusercontent.com/79368885/196080912-26634840-59af-42fb-b2fa-6675ef8f4312.png) is the prob of class K，why 
![图片](https://user-images.githubusercontent.com/79368885/196081017-4f58f7e2-9017-428d-a6c2-a8ed380777f3.png)?
I would appreciate it if you could answer my question.

**Comment by jiawei-ren** [comment]
It is by definition. Please refer to Sect 3.2.3 in [this note](https://cs229.stanford.edu/lectures-spring2022/main_notes.pdf).

**Comment by madoka109** [comment]
> It is by definition. Please refer to Sect 3.2.3 in [this note](https://cs229.stanford.edu/lectures-spring2022/main_notes.pdf).

Thanks a lot!
