### ISSUE TITLE
I have one question about sample_per_class in balanced_softmax_loss

### ISSUE THREAD

**Issue by Bhongcheng** [jiawei-ren/BalancedMetaSoftmax-Classification#15]
Dear friend, I wonder what would happen if there are "0" in sample_per_class(missing class), as 0.log() is -inf. In that case, what is the meaning of it? Could you please inform me?

**Comment by jiawei-ren** [comment]
If there are unseen classes with 0 samples in training, it will be a zero-shot problem where our method is no longer applicable.
