### ISSUE TITLE
Question about many shot acc and Evaluation_accuracy_micro_top1

### ISSUE THREAD

**Issue by e96031413** [jiawei-ren/BalancedMetaSoftmax-Classification#8]
Hello, I am curious about the difference between **Many_shot_accuracy_top1** and **Evaluation_accuracy_micro_top1** in the testing phase.

If I train with a dataset that has 6 class, and each class contains over 100 images, there will only Many_shot_accuracy_top1 in the testing output.

My question is "why the value of **Many_shot_accuracy_top1** and **Evaluation_accuracy_micro_top1** are different ?" Should't they be the same, since all the class contains over 100 images? or I misunderstand these 2 metrics?

**Comment by jiawei-ren** [comment]
Sorry for the late reply. **Many_shot_accuracy_top1** averages over classes while **Evaluation_accuracy_micro_top1** averages over images. They will have different values if labels are not uniformly distributed in the test set.

**Comment by e96031413** [comment]
@jiawei-ren Thanks for your reply.
