### ISSUE TITLE
Where can I get the data listed in ImageNet_LT.txt?

### ISSUE THREAD

**Issue by 18445864529** [jiawei-ren/BalancedMetaSoftmax-Classification#9]
where can I download the data that looks like these?
```
train/n01440764/n01440764_190.JPEG 0
val/n01440764/ILSVRC2012_val_00017700.JPEG 0
```
I checked both this link
https://drive.google.com/drive/u/0/folders/1j7Nkfe6ZhzKFXePHdsseeeGI877Xu1yf
and the ImageNet official site
https://image-net.org/challenges/LSVRC/2014/2014-downloads.php
but cannot find one that corresponds to the format.

Could someone point me out please?

**Comment by jiawei-ren** [comment]
Since the issue description is not very clear and no one else has encountered a similar issue so far, I will close the issue for now. Feel free to add more description and re-open it.
